name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Show system info
        run: |
          echo "OS: Windows"
          systeminfo | findstr /C:"OS Name"
          java -version
